# Generated by Django 4.2.4 on 2023-08-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userQuest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Favorite_Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userQuest.favoritequestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='Read_Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userQuest.readquestion'),
        ),
    ]
